# Generated by Django 4.2.7 on 2023-11-16 15:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="worker",
            options={
                "ordering": ["id"],
                "verbose_name": "worker",
                "verbose_name_plural": "workers",
            },
        ),
    ]
