# Generated by Django 4.2.7 on 2023-11-16 15:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0002_alter_worker_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="position",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["id"]},
        ),
    ]
