# Generated by Django 4.2.7 on 2023-11-17 16:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0003_alter_position_options_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tasktype",
            options={"ordering": ["id"]},
        ),
    ]
